### ISSUE TITLE
Login Page and Sign Up Page Design needed

### ISSUE THREAD

**Issue by j-jimenez01** [Safe-Reach/FrontEnd#5]
Design the pages. Don't worry about backend connection yet

**Comment by Dimpal273** [comment]
**Login**
![Login](https://github.com/Safe-Reach/FrontEnd/assets/72816486/23d50618-7523-4b52-b1a0-7f028a56581e)

**Signup**
![Signup](https://github.com/Safe-Reach/FrontEnd/assets/72816486/212ad2f4-c055-4e27-b975-f45107985a01)
