### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by j-jimenez01** [Safe-Reach/FrontEnd#7]
General Idea of what app will look like

**Comment by Dimpal273** [comment]
**Login**
<img width="288" alt="Login" src="https://github.com/Safe-Reach/FrontEnd/assets/72816486/d5330934-546f-4a82-8858-23403a16d152">

**Signup**
<img width="271" alt="Signup" src="https://github.com/Safe-Reach/FrontEnd/assets/72816486/2dd53aad-b2ae-43d9-92a3-9d090ba29ca3">

**Home**
<img width="265" alt="Home" src="https://github.com/Safe-Reach/FrontEnd/assets/72816486/b0e8d21f-73bd-49a6-9dd9-7bc8a3fda6fc">

**Profile**
<img width="265" alt="Profile" src="https://github.com/Safe-Reach/FrontEnd/assets/72816486/f2ac2725-b4da-43f2-8602-bbbed85b13a8">
