### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by j-jimenez01** [Safe-Reach/FrontEnd#8]
Need to come up with logo designs and theme color

**Comment by Dimpal273** [comment]
**Logo**
<img width="215" alt="Safe-Reach Logo" src="https://github.com/Safe-Reach/FrontEnd/assets/72816486/98bf441d-7aef-4460-a6d6-425246c02e38">

**Comment by Dimpal273** [comment]
**Theme colors**
Turquoise, black, white, gray
